// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/work.proto

//
//ID int64 `gorm:"primary_key;auto_increment;not_null" json:"id"`
//Name string `json:"name"`
//Nums string `json:"nums"`//工号
//Sex string `json:"sex"` //性别
//Level int64 `json:"level"`//等级
//Score int64 `json:"score"`//信誉分
//Place string `json:"place"`//住址
//Telephone string `json:"telephone"`//电话
//Mail string `json:"mail"`
//Description string `json:"description"`//补充描述
//ISWork bool `json:"is_work"`//是否在职

package work

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Work service

func NewWorkEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Work service

type WorkService interface {
	CreateWorker(ctx context.Context, in *Request_Workers, opts ...client.CallOption) (*Response_CreateWorker, error)
	UpdateWorker(ctx context.Context, in *Request_Workers, opts ...client.CallOption) (*Response_CreateWorker, error)
	DeleteWorkerByID(ctx context.Context, in *Request_Workers_ID, opts ...client.CallOption) (*Response_Workers, error)
	FindWorkerByID(ctx context.Context, in *Request_Workers_ID, opts ...client.CallOption) (*Response_Worker_Show, error)
	FindWorkerByName(ctx context.Context, in *Request_Workers_Name, opts ...client.CallOption) (*Response_Workers_Show, error)
	FindAll(ctx context.Context, in *Request_Null, opts ...client.CallOption) (*Response_Workers_Show, error)
	CreateToken(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
}

type workService struct {
	c    client.Client
	name string
}

func NewWorkService(name string, c client.Client) WorkService {
	return &workService{
		c:    c,
		name: name,
	}
}

func (c *workService) CreateWorker(ctx context.Context, in *Request_Workers, opts ...client.CallOption) (*Response_CreateWorker, error) {
	req := c.c.NewRequest(c.name, "Work.CreateWorker", in)
	out := new(Response_CreateWorker)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workService) UpdateWorker(ctx context.Context, in *Request_Workers, opts ...client.CallOption) (*Response_CreateWorker, error) {
	req := c.c.NewRequest(c.name, "Work.UpdateWorker", in)
	out := new(Response_CreateWorker)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workService) DeleteWorkerByID(ctx context.Context, in *Request_Workers_ID, opts ...client.CallOption) (*Response_Workers, error) {
	req := c.c.NewRequest(c.name, "Work.DeleteWorkerByID", in)
	out := new(Response_Workers)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workService) FindWorkerByID(ctx context.Context, in *Request_Workers_ID, opts ...client.CallOption) (*Response_Worker_Show, error) {
	req := c.c.NewRequest(c.name, "Work.FindWorkerByID", in)
	out := new(Response_Worker_Show)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workService) FindWorkerByName(ctx context.Context, in *Request_Workers_Name, opts ...client.CallOption) (*Response_Workers_Show, error) {
	req := c.c.NewRequest(c.name, "Work.FindWorkerByName", in)
	out := new(Response_Workers_Show)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workService) FindAll(ctx context.Context, in *Request_Null, opts ...client.CallOption) (*Response_Workers_Show, error) {
	req := c.c.NewRequest(c.name, "Work.FindAll", in)
	out := new(Response_Workers_Show)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workService) CreateToken(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "Work.CreateToken", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Work service

type WorkHandler interface {
	CreateWorker(context.Context, *Request_Workers, *Response_CreateWorker) error
	UpdateWorker(context.Context, *Request_Workers, *Response_CreateWorker) error
	DeleteWorkerByID(context.Context, *Request_Workers_ID, *Response_Workers) error
	FindWorkerByID(context.Context, *Request_Workers_ID, *Response_Worker_Show) error
	FindWorkerByName(context.Context, *Request_Workers_Name, *Response_Workers_Show) error
	FindAll(context.Context, *Request_Null, *Response_Workers_Show) error
	CreateToken(context.Context, *LoginRequest, *LoginResponse) error
}

func RegisterWorkHandler(s server.Server, hdlr WorkHandler, opts ...server.HandlerOption) error {
	type work interface {
		CreateWorker(ctx context.Context, in *Request_Workers, out *Response_CreateWorker) error
		UpdateWorker(ctx context.Context, in *Request_Workers, out *Response_CreateWorker) error
		DeleteWorkerByID(ctx context.Context, in *Request_Workers_ID, out *Response_Workers) error
		FindWorkerByID(ctx context.Context, in *Request_Workers_ID, out *Response_Worker_Show) error
		FindWorkerByName(ctx context.Context, in *Request_Workers_Name, out *Response_Workers_Show) error
		FindAll(ctx context.Context, in *Request_Null, out *Response_Workers_Show) error
		CreateToken(ctx context.Context, in *LoginRequest, out *LoginResponse) error
	}
	type Work struct {
		work
	}
	h := &workHandler{hdlr}
	return s.Handle(s.NewHandler(&Work{h}, opts...))
}

type workHandler struct {
	WorkHandler
}

func (h *workHandler) CreateWorker(ctx context.Context, in *Request_Workers, out *Response_CreateWorker) error {
	return h.WorkHandler.CreateWorker(ctx, in, out)
}

func (h *workHandler) UpdateWorker(ctx context.Context, in *Request_Workers, out *Response_CreateWorker) error {
	return h.WorkHandler.UpdateWorker(ctx, in, out)
}

func (h *workHandler) DeleteWorkerByID(ctx context.Context, in *Request_Workers_ID, out *Response_Workers) error {
	return h.WorkHandler.DeleteWorkerByID(ctx, in, out)
}

func (h *workHandler) FindWorkerByID(ctx context.Context, in *Request_Workers_ID, out *Response_Worker_Show) error {
	return h.WorkHandler.FindWorkerByID(ctx, in, out)
}

func (h *workHandler) FindWorkerByName(ctx context.Context, in *Request_Workers_Name, out *Response_Workers_Show) error {
	return h.WorkHandler.FindWorkerByName(ctx, in, out)
}

func (h *workHandler) FindAll(ctx context.Context, in *Request_Null, out *Response_Workers_Show) error {
	return h.WorkHandler.FindAll(ctx, in, out)
}

func (h *workHandler) CreateToken(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.WorkHandler.CreateToken(ctx, in, out)
}
